# Generated by Django 2.2 on 2020-03-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNum', models.CharField(max_length=4)),
                ('division', models.CharField(choices=[('Latemodel', 'Latemodel'), ('Jr latemodel', 'Jr latemodel'), ('Limited modifieds', 'Limited modifieds'), ('Super Stock', 'Super Stock'), ('F4', 'F4'), ('Mini Cup / Bandoleros', 'Mini Cup / Bandoleros'), ('Trailer', 'Trailer'), ('UTV', 'UTV'), ('Enduro', 'Enduro')], max_length=20)),
                ('engine', models.CharField(max_length=20)),
                ('driver', models.CharField(max_length=100)),
                ('carMake', models.CharField(max_length=100)),
                ('requiredWeight', models.IntegerField()),
                ('minleftSideWeight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('carOwner', models.CharField(max_length=100)),
                ('messageNumber', models.CharField(max_length=11)),
            ],
        ),
    ]
