# Generated by Django 2.2 on 2020-03-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20200324_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_racing',
            field=models.BooleanField(default=False),
        ),
    ]
