# Generated by Django 2.2 on 2020-03-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saftey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNum', models.CharField(max_length=3)),
                ('division', models.CharField(max_length=20)),
                ('helmetDate', models.CharField(max_length=20)),
                ('seatbeltDate', models.CharField(max_length=20)),
                ('windowNet', models.CharField(max_length=20)),
                ('headAndNeck', models.CharField(max_length=20)),
                ('fireSuite', models.CharField(max_length=20)),
                ('gloves', models.CharField(max_length=20)),
                ('shoes', models.CharField(max_length=20)),
                ('seat', models.CharField(max_length=20)),
                ('firesystem', models.CharField(max_length=20)),
                ('radio', models.CharField(max_length=20)),
                ('transponder', models.CharField(max_length=20)),
                ('drivelineLoop', models.CharField(max_length=20)),
                ('sideExhaust', models.CharField(max_length=20)),
                ('masterKill', models.CharField(max_length=20)),
                ('fuelLines', models.CharField(max_length=20)),
                ('fuelCellHeight', models.CharField(max_length=20)),
                ('colapsableCoulum', models.CharField(max_length=20)),
                ('cage', models.CharField(max_length=20)),
                ('weightBlocks', models.CharField(max_length=20)),
                ('drivelinepainted', models.CharField(max_length=20)),
                ('notes', models.TextField(max_length=20)),
            ],
        ),
    ]
