# Generated by Django 2.2 on 2020-03-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saftey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saftey',
            name='recheck',
            field=models.TextField(default='False', max_length=20),
        ),
    ]
