# Generated by Django 2.2.11 on 2020-03-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saftey', '0002_saftey_recheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saftey',
            name='cage',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='colapsableCoulum',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='division',
            field=models.CharField(choices=[('latemodel', 'Latemodel'), ('jr latemodel', 'Jr latemodel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='drivelineLoop',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='drivelinepainted',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='fireSuite',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='firesystem',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='fuelCellHeight',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='fuelLines',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='gloves',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='headAndNeck',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='helmetDate',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='masterKill',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='radio',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='recheck',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='seat',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='seatbeltDate',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='shoes',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='sideExhaust',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='transponder',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='weightBlocks',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='windowNet',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20),
        ),
    ]
