# Generated by Django 2.2.11 on 2020-03-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saftey', '0003_auto_20200323_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='saftey',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
