# Generated by Django 2.2.11 on 2020-03-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saftey', '0004_saftey_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saftey',
            name='division',
            field=models.CharField(choices=[('latemodel', 'Latemodel'), ('jr latemodel', 'Jr latemodel'), ('limited modifieds', 'Limited modifieds'), ('super stock', 'Super Stock'), ('f4', 'F4'), ('mini cup', 'Mini Cup / Bandoleros'), ('trailer', 'Trailer'), ('utv', 'UTV'), ('enduro', 'Enduro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saftey',
            name='helmetDate',
            field=models.CharField(choices=[('sa2012', 'SA2020'), ('sa2015', 'SA2015'), ('sa2010', 'SA2010'), ('out datad', 'Out Dated')], max_length=20),
        ),
    ]
