# Generated by Django 2.2.11 on 2020-03-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saftey', '0005_auto_20200323_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saftey',
            name='seatbeltDate',
            field=models.DateField(),
        ),
    ]
