# Generated by Django 2.2.11 on 2020-03-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saftey', '0007_auto_20200324_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saftey',
            name='created_at',
        ),
    ]
