# Generated by Django 2.2.11 on 2020-03-24 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saftey', '0009_auto_20200324_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='saftey',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
