# Generated by Django 2.2.11 on 2020-03-24 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saftey', '0010_saftey_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saftey',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
