# Generated by Django 2.2.11 on 2020-03-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.IntegerField(max_length=3)),
                ('carNum', models.IntegerField(max_length=4)),
                ('preQualifingWeight', models.IntegerField(max_length=4)),
                ('preQualifingLeft', models.IntegerField(max_length=4)),
                ('raceStartWeight', models.IntegerField(max_length=4)),
                ('raceStartLeft', models.IntegerField(max_length=4)),
                ('midRaceStart', models.IntegerField(max_length=4)),
                ('midRaceLeft', models.IntegerField(max_length=4)),
            ],
        ),
    ]
