# Generated by Django 2.2 on 2020-03-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scales',
            name='carNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scales',
            name='midRaceLeft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scales',
            name='midRaceStart',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scales',
            name='preQualifingLeft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scales',
            name='preQualifingWeight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scales',
            name='race',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scales',
            name='raceStartLeft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scales',
            name='raceStartWeight',
            field=models.IntegerField(),
        ),
    ]
