# Generated by Django 2.2 on 2020-03-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0003_auto_20200324_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scales',
            name='carNum',
            field=models.CharField(max_length=4),
        ),
    ]
