# Generated by Django 2.2 on 2020-03-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0005_auto_20200324_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='scales',
            name='division',
            field=models.CharField(choices=[('Latemodel', 'Latemodel'), ('Jr latemodel', 'Jr latemodel'), ('Limited modifieds', 'Limited modifieds'), ('Super Stock', 'Super Stock'), ('F4', 'F4'), ('Mini Cup / Bandoleros', 'Mini Cup / Bandoleros'), ('Trailer', 'Trailer'), ('UTV', 'UTV'), ('Enduro', 'Enduro')], default='Latemodel', max_length=20),
            preserve_default=False,
        ),
    ]
